### ISSUE TITLE
Authenticate with GitHub to access private repositories

### ISSUE THREAD

**Issue by jjmark15** [jjmark15/tidy-repo#5]
# Background
Currently we cannot make queries to GitHub for repositories that are private.

# Requirements
- Be able to authenticate with GitHub
- New authentications should overwrite previous
- Be able to make queries for private repositories when authenticated
- Being authenticated should be optional
  - Functionality for querying public repositories should remain unchanged

# Implementation
- Make use of GitHub OAuth to use the GitHub API for private repositories
- Add command to authenticate with GitHub
  - store a personal access token (PAT)
    - store PATs in `~/.tidy_repo/config.yml`
  - validate PAT with GitHub by sending [basic authed request](https://developer.github.com/v3/#oauth2-token-sent-in-a-header)

## Command
- Inline: `tidy-repo authenticate github --token <TOKEN>`
- Interactive: `tidy-repo authenticate github`
  - then prompt for token

# Resources
https://developer.github.com/v3/#authentication

**Comment by jjmark15** [comment]
# Thoughts
- where should tests live?
  - [x] query public/private repository with/without authorization token - thinking they should just live in a submodule of `branches`
## Authenticate

- directly interact with authentication service
- send a request to verify creds
  - require an injected client?
  - need a way to set credentials on a request
    - could pass creds with each method but this seems clunky and adds to the interface which is probably not appropriate as would not necessarily make sense for all implementations
    - might be better to have a method on `RepoHost` to mutably set creds on client
      - when should this be done? could do it at repeatedly at time of each request but this seems extra. Could have wrapper object in domain that manages it's own lifecycle and sets up auth. This could then be injected with the auth service directly
- store creds
  - require an injected persistence manager

## Send authenticated request

- indirectly interact
- other services such as branch counting service need to be injected with auth service?
  - alternative would be injecting them with a pre-authenticated client
    - not so keen on this as construction of the github client happens before we enter the application layer

**Comment by jjmark15** [comment]
# ToDo
- [x] handle case of wrong command options requested in run method
- [x] add unhappy integration tests
- [x] test case of app home directory not existing
- [x] fix `~` not working as reference to home directory for app home directory
- [x] add tests for with/without auth token
- [x] credential persistence
- [x] credential verification
- [x] test case of overwriting credentials
- add interactive token entry - raise new card #8
